// Autogenerated. Code generated by thrift-gen. Do not modify.
package stream

import (
	"fmt"

	athrift "github.com/apache/thrift/lib/go/thrift"
	"github.com/uber/tchannel-go/thrift"
)

// Interfaces for the service and client for the services defined in the IDL.

type TChanTestStream interface {
}

// Implementation of a client and service handler.

type tchanTestStreamClient struct {
	thriftService string
	client        thrift.TChanClient
}

func newTChanTestStreamClient(thriftService string, client thrift.TChanClient) *tchanTestStreamClient {
	return &tchanTestStreamClient{
		thriftService,
		client,
	}
}

func NewTChanTestStreamClient(client thrift.TChanClient) TChanTestStream {
	return newTChanTestStreamClient("TestStream", client)
}

type tchanTestStreamServer struct {
	handler TChanTestStream
}

func newTChanTestStreamServer(handler TChanTestStream) *tchanTestStreamServer {
	return &tchanTestStreamServer{
		handler,
	}
}

func NewTChanTestStreamServer(handler TChanTestStream) thrift.TChanServer {
	return newTChanTestStreamServer(handler)
}

func (s *tchanTestStreamServer) Service() string {
	return "TestStream"
}

func (s *tchanTestStreamServer) Methods() []string {
	return []string{}
}

func (s *tchanTestStreamServer) Handle(ctx thrift.Context, methodName string, protocol athrift.TProtocol) (bool, athrift.TStruct, error) {
	switch methodName {

	default:
		return false, nil, fmt.Errorf("method %v not found in service %v", methodName, s.Service())
	}
}
